server:
  port: 8090
spring:
  application:
    name: test_solva
  datasource:
    url: jdbc:postgresql://localhost:5434/exchange_rate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
integration:
  url: https://nationalbank.kz/rss/get_rates.cfm
